import pytest

from page_objects.admin_customers_page import AdminCustomerPage
from page_objects.admin_page import AdminPage
from page_objects.elements.admin_navigator_menu import AdminNavigatorMenu


def test_add_customer(browser, url):
    admin_customer_page = AdminPage(browser)
    admin_customer_page.open(url)
    admin_customer_page.login_admin("user", "bitnami")
    admin_customer_page = AdminNavigatorMenu(browser)
    admin_customer_page.open_customer_catalog()
    admin_customer_page = AdminCustomerPage(browser)
    admin_customer_page.click_add_customers_button()
    admin_customer_page.input_first_name("Igor")
    admin_customer_page.input_last_name("Petrov")
    admin_customer_page.input_email()
    admin_customer_page.input_telephone()
    admin_customer_page.input_password("test")
    admin_customer_page.input_confirm_password("test")
    admin_customer_page.click_save_button()
    admin_customer_page.verify_success_message()


def test_delete_customer(browser, url):
    test_add_customer(browser, url)
    admin_customer_page = AdminCustomerPage(browser)
    admin_customer_page.find_customers_name("Igor Petrov")
    admin_customer_page.click_filter_button()
    admin_customer_page.click_check_box()
    admin_customer_page.click_delete_customers_button()
    admin_customer_page.alert_delete_product(browser)
    admin_customer_page.verify_success_message()


def test_incorrect_email(browser, url):
    admin_customer_page = AdminPage(browser)
    admin_customer_page.open(url)
    admin_customer_page.login_admin("user", "bitnami")
    admin_customer_page = AdminNavigatorMenu(browser)
    admin_customer_page.open_customer_catalog()
    admin_customer_page = AdminCustomerPage(browser)
    admin_customer_page.click_add_customers_button()
    admin_customer_page.input_first_name("Igor")
    admin_customer_page.input_last_name("Petrov")
    admin_customer_page.input_incorrect_email()
    admin_customer_page.input_telephone()
    admin_customer_page.input_password("test")
    admin_customer_page.input_confirm_password("test")
    admin_customer_page.click_save_button()
    admin_customer_page.verify_warning_message()
    admin_customer_page.verify_error_message_email()


def test_empty_first_name(browser, url):
    admin_customer_page = AdminPage(browser)
    admin_customer_page.open(url)
    admin_customer_page.login_admin("user", "bitnami")
    admin_customer_page = AdminNavigatorMenu(browser)
    admin_customer_page.open_customer_catalog()
    admin_customer_page = AdminCustomerPage(browser)
    admin_customer_page.click_add_customers_button()
    admin_customer_page.input_last_name("Petrov")
    admin_customer_page.input_email()
    admin_customer_page.input_telephone()
    admin_customer_page.input_password("test")
    admin_customer_page.input_confirm_password("test")
    admin_customer_page.click_save_button()
    admin_customer_page.verify_warning_message()
    admin_customer_page.verify_error_message_first_name()


def test_long_first_name(browser, url):
    admin_customer_page = AdminPage(browser)
    admin_customer_page.open(url)
    admin_customer_page.login_admin("user", "bitnami")
    admin_customer_page = AdminNavigatorMenu(browser)
    admin_customer_page.open_customer_catalog()
    admin_customer_page = AdminCustomerPage(browser)
    admin_customer_page.click_add_customers_button()
    admin_customer_page.input_long_first_name()
    admin_customer_page.input_last_name("Petrov")
    admin_customer_page.input_email()
    admin_customer_page.input_telephone()
    admin_customer_page.input_password("test")
    admin_customer_page.input_confirm_password("test")
    admin_customer_page.click_save_button()
    admin_customer_page.verify_warning_message()
    admin_customer_page.verify_error_message_first_name()


def test_empty_last_name(browser, url):
    admin_customer_page = AdminPage(browser)
    admin_customer_page.open(url)
    admin_customer_page.login_admin("user", "bitnami")
    admin_customer_page = AdminNavigatorMenu(browser)
    admin_customer_page.open_customer_catalog()
    admin_customer_page = AdminCustomerPage(browser)
    admin_customer_page.click_add_customers_button()
    admin_customer_page.input_first_name("Igor")
    admin_customer_page.input_email()
    admin_customer_page.input_telephone()
    admin_customer_page.input_password("test")
    admin_customer_page.input_confirm_password("test")
    admin_customer_page.click_save_button()
    admin_customer_page.verify_warning_message()
    admin_customer_page.verify_error_message_last_name()


def test_long_last_name(browser, url):
    admin_customer_page = AdminPage(browser)
    admin_customer_page.open(url)
    admin_customer_page.login_admin("user", "bitnami")
    admin_customer_page = AdminNavigatorMenu(browser)
    admin_customer_page.open_customer_catalog()
    admin_customer_page = AdminCustomerPage(browser)
    admin_customer_page.click_add_customers_button()
    admin_customer_page.input_first_name("Igor")
    admin_customer_page.input_long_last_name()
    admin_customer_page.input_email()
    admin_customer_page.input_telephone()
    admin_customer_page.input_password("test")
    admin_customer_page.input_confirm_password("test")
    admin_customer_page.click_save_button()
    admin_customer_page.verify_warning_message()
    admin_customer_page.verify_error_message_last_name()


def test_shot_telephone(browser, url):
    admin_customer_page = AdminPage(browser)
    admin_customer_page.open(url)
    admin_customer_page.login_admin("user", "bitnami")
    admin_customer_page = AdminNavigatorMenu(browser)
    admin_customer_page.open_customer_catalog()
    admin_customer_page = AdminCustomerPage(browser)
    admin_customer_page.click_add_customers_button()
    admin_customer_page.input_first_name("Igor")
    admin_customer_page.input_last_name("Petrov")
    admin_customer_page.input_email()
    admin_customer_page.input_short_telephone()
    admin_customer_page.input_password("test")
    admin_customer_page.input_confirm_password("test")
    admin_customer_page.click_save_button()
    admin_customer_page.verify_warning_message()
    admin_customer_page.verify_error_message_telephone()


def test_long_telephone(browser, url):
    admin_customer_page = AdminPage(browser)
    admin_customer_page.open(url)
    admin_customer_page.login_admin("user", "bitnami")
    admin_customer_page = AdminNavigatorMenu(browser)
    admin_customer_page.open_customer_catalog()
    admin_customer_page = AdminCustomerPage(browser)
    admin_customer_page.click_add_customers_button()
    admin_customer_page.input_first_name("Igor")
    admin_customer_page.input_last_name("Petrov")
    admin_customer_page.input_email()
    admin_customer_page.input_long_telephone()
    admin_customer_page.input_password("test")
    admin_customer_page.input_confirm_password("test")
    admin_customer_page.click_save_button()
    admin_customer_page.verify_warning_message()
    admin_customer_page.verify_error_message_telephone()


def test_shot_password(browser, url):
    admin_customer_page = AdminPage(browser)
    admin_customer_page.open(url)
    admin_customer_page.login_admin("user", "bitnami")
    admin_customer_page = AdminNavigatorMenu(browser)
    admin_customer_page.open_customer_catalog()
    admin_customer_page = AdminCustomerPage(browser)
    admin_customer_page.click_add_customers_button()
    admin_customer_page.input_first_name("Igor")
    admin_customer_page.input_last_name("Petrov")
    admin_customer_page.input_email()
    admin_customer_page.input_telephone()
    admin_customer_page.input_shot_password()
    admin_customer_page.click_save_button()
    admin_customer_page.verify_warning_message()
    admin_customer_page.verify_error_message_password()


# а этот кейс не проходит, т.к. бага в опенкарте, написано, что пароль до 20 символов, я ввожу 21 символ и ошибки не появляется.
@pytest.mark.xfail(strict=True)
def test_long_password(browser, url):
    admin_customer_page = AdminPage(browser)
    admin_customer_page.open(url)
    admin_customer_page.login_admin("user", "bitnami")
    admin_customer_page = AdminNavigatorMenu(browser)
    admin_customer_page.open_customer_catalog()
    admin_customer_page = AdminCustomerPage(browser)
    admin_customer_page.click_add_customers_button()
    admin_customer_page.input_first_name("Igor")
    admin_customer_page.input_last_name("Petrov")
    admin_customer_page.input_email()
    admin_customer_page.input_telephone()
    admin_customer_page.input_long_password()
    admin_customer_page.click_save_button()
    admin_customer_page.verify_warning_message()
    admin_customer_page.verify_error_message_password()


def test_password_and_confirmation_different(browser, url):
    admin_customer_page = AdminPage(browser)
    admin_customer_page.open(url)
    admin_customer_page.login_admin("user", "bitnami")
    admin_customer_page = AdminNavigatorMenu(browser)
    admin_customer_page.open_customer_catalog()
    admin_customer_page = AdminCustomerPage(browser)
    admin_customer_page.click_add_customers_button()
    admin_customer_page.input_first_name("Igor")
    admin_customer_page.input_last_name("Petrov")
    admin_customer_page.input_email()
    admin_customer_page.input_telephone()
    admin_customer_page.input_random_password()
    admin_customer_page.input_random_confirm_password()
    admin_customer_page.click_save_button()
    admin_customer_page.verify_warning_message()
    admin_customer_page.verify_error_message_confirmation()
